# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default=b'homepage/image/background.png', upload_to=b'static'),
        ),
    ]
